
services:
  postgres:
    image: postgres:15.5
    container_name: postgres-task
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: task-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: