server:
  port: 8081

spring:
  application:
    name: "tracker-auth"

  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

Kafka:
  topic: ${KAFKA_TOPIC_NAME}

internal:
  api-key: ${INTERNAL_API_KEY}