server:
  port: 8081

spring:
  application:
    name: "tracker-auth"

  datasource:
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task-db

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret: "123456789123456789werwefdsvwdvwwfwe"
  expiration: 86400000